### ISSUE TITLE
Add a "Code of conduct" and "CONTRIBUTING.md"

### ISSUE THREAD

**Issue by animenon** [techfaqs/Tech-FAQs#4]
For `Code of Conduct` refer: https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/
For `CONTRIBUTING.md` refer: https://help.github.com/articles/setting-guidelines-for-repository-contributors/

Sample Refer: https://github.com/atom/atom/blob/master/CONTRIBUTING.md

**Comment by codingCookie** [comment]
hey - I'm on it :)

**Comment by animenon** [comment]
That was great @codingCookie .
